### ISSUE TITLE
How to using

### ISSUE THREAD

**Issue by xthaohg** [rishi420/ExpandableTableView#2]
Hey! thanks bro for share. I was imported your project but it not running as your gift.
Excuse me for translate

**Comment by xthaohg** [comment]
it no header.

**Comment by rishi420** [comment]
Hey @xthaohg thanks for informing me. The project was made with Xcode 7.2 which supports swift 2.2 only. May be that is the reason. I have plan to update this project with Xcode 8 and swift 3 next week.

**Comment by xthaohg** [comment]
@rishi420 I see your project 100% objective. 
You can support using this?

**Comment by rishi420** [comment]
@xthaohg I won't convert this project to swift 3. The problem is fixed with the latest commit. please check and close the issue if fixed. :)

**Comment by xthaohg** [comment]
Thanks bro. I want your project using objective c.

**Comment by rishi420** [comment]
@xthaohg is the issue solved?

**Comment by xthaohg** [comment]
Ok. Thanks for your supportting

Vào Chủ Nhật, ngày 16 tháng 10 năm 2016, Warif Akhand Rishi <
notifications@github.com> đã viết:
