### ISSUE TITLE
App crash when tap on Header.

### ISSUE THREAD

**Issue by milanivarni** [rishi420/ExpandableTableView#3]
HI, I am new in iOS.
Recently I used on this library in my project. I have two NSMutableArray:
(1) questionArray -> 11 Objects
(2) answerArray -> 11 Objects

I wrote following code:
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
  
  return **[self.tableView totalNumberOfRows:1 inSection:section];**
  }
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
  
  UITableViewCell _cell = [tableView dequeueReusableCellWithIdentifier:@"Cell"];
  cell.textLabel.text =  *_answerArray**[indexPath.row];
  return cell;
  }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
  
  return **questionsArray.count;**
  }
# pragma mark - UITableViewDelegate
- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section {
  return HEADER_VIEW_HEIGHT;
  }
- (nullable UIView _)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {
  return *_[self.tableView headerWithTitle:questionsArray[section] totalRows:1 inSection:section];**
  }

there is some layout issues for cells.

![simulator screen shot 13-oct-2016 3 35 02 pm](https://cloud.githubusercontent.com/assets/22673922/19345120/a4baf220-915a-11e6-85de-fad090b1c6f8.png)
*\* (<FAQController: 0x7fd36d44b740>)

when I tap on particular header. App stuck on [self endUpdates] and crashed.
I got following error:

 **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UITableView (<ExpandableTableView: 0x7fd3689a9e00; baseClass = UITableView; frame = (0 0; 320 568); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x7fd36d4d5150>; layer = <CALayer: 0x7fd36a9c0cc0>; contentOffset: {0, 0}; contentSize: {320, 550}>) **failed to obtain a cell from its dataSource

So, please help me out from this.

Thanks.

**Comment by rishi420** [comment]
I've updated this repository for Xcode 8 today. Is it crashing on latest build? Which version of xcode are you using?

**Comment by rishi420** [comment]
@milanivarni Is the issue solved? Latest code is for Xcode 8. If you are using Xcode 7.2 you can download older release from https://github.com/rishi420/ExpandableTableView/releases.

**Comment by rishi420** [comment]
Issue did not reproduce in latest code. Issuer is not responding.
